// --- Task ---

export interface TaskDetail {
  id: string;
  /** Brief title, max 10 chars, generated by LLM when creating the task. */
  title: string;
  description: string;
  priority: 'normal' | 'high';
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';
  createdAt: number;
  startedAt?: number;
  completedAt?: number;
  result?: string;
  error?: string;
  workerSessionId?: string;
  /** Worker type: 'puppet' (default) or a configured worker ID (e.g. 'claude-code'). */
  workerType?: string;
}
